kind: Pod
apiVersion: v1
metadata:
  name: pod-emptydir-oom
  labels:
    name: pod-emptydir-oom
spec:
  containers:
  - name: c1
    image: docker.io/ocpqe/hello-pod
    ports:
    - containerPort: 8080
      protocol: TCP
    resources:
      limits:
        memory: 1Gi
        cpu: 500m
    command:
    - dd
    - if=/dev/zero
    - of=/mnt/zero
    - bs=1M
    - count=2000
    volumeMounts:
    - name: myvol
      mountPath: "/mnt"
    terminationMessagePath: "/dev/termination-log"
    imagePullPolicy: IfNotPresent
  volumes:
  - name: myvol
    emptyDir:
      medium: Memory
  restartPolicy: Always
