apiVersion: v1
kind: Pod
metadata:
  name: test-pd
spec:
  containers:
  - image: aosqe/hello-openshift
    name: test-container
    volumeMounts:
    - mountPath: /test-pd
      name: test-volume
    securityContext:
      privileged: true
  volumes:
  - name: test-volume
    hostPath:
      path: /tmp
