apiVersion: v1
kind: Pod
metadata:
  name: pod-secret-datastring-data-image-volume
  labels:
    name: pod-secret-datastring-data-image-volume
spec:
  containers:
  - name: pod-secret-datastring-data-image-volume
    image: docker.io/ocpqe/hello-pod:latest
    env:
    - name: MYSQL_USER
      value: userSUM
      name: MYSQL_PASSWORD
      value: P5J6s8wf
      name: MYSQL_DATABASE
      value: root
      name: MYSQL_ROOT_PASSWORD
      value: W5J6s8wf
    volumeMounts:
    - name: secret-volume
      mountPath: /etc/secret-volume
      readOnly: true
  volumes:
  - name: secret-volume
    secret:
      secretName: secret-datastring-data-image
