apiVersion: v1
kind: ResourceQuota
metadata:
  name: quota-precious-resource
spec:
  hard:
    persistentvolumeclaims: "10"
    requests.cpu: "4"
    requests.storage: "50Gi"
    gold.storageclass.storage.k8s.io/requests.storage: "5Gi"
