apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    run: resource-consumer
  name: resource-consumer
spec:
  replicas: 1
  selector:
    run: resource-consumer
  template:
    metadata:
      labels:
        run: resource-consumer
    spec:
        containers:
        - image: docker.io/ocpqe/resource_consumer:v1
          imagePullPolicy: Always
          name: resource-consumer
          ports:
          - containerPort: 8080
            protocol: TCP
          resources:
            requests:
              cpu: 100m
              memory: 150Mi
            limits:
              cpu: 200m
              memory: 250Mi
          terminationMessagePath: /dev/termination-log
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
        terminationGracePeriodSeconds: 30
